#cloud-config
package_update: true
package_upgrade: true
packages:
  - apache2
  - mysql-server
  - php
  - php-mysql
  - libapache2-mod-php
  - wget
  - unzip

runcmd:
  # Create MySQL DB and user
  - mysql -e "CREATE DATABASE wordpress;"
  - mysql -e "CREATE USER 'wpuser'@'localhost' IDENTIFIED BY 'ilikemanutd95';"
  - mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"

  # Remove default Apache page
  - rm -f /var/www/html/index.html

  # Download and configure WordPress
  - wget https://wordpress.org/latest.zip -O /tmp/wordpress.zip
  - unzip /tmp/wordpress.zip -d /tmp
  - cp -r /tmp/wordpress/* /var/www/html/

  # Create wp-config.php from sample
  - cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  - sed -i "s/database_name_here/wordpress/" /var/www/html/wp-config.php
  - sed -i "s/username_here/wpuser/" /var/www/html/wp-config.php
  - sed -i "s/password_here/ilikemanutd95/" /var/www/html/wp-config.php

  # Set permissions
  - chown -R www-data:www-data /var/www/html
  - chmod -R 755 /var/www/html

  # Restart Apache
  - systemctl enable apache2
  - systemctl restart apache2
